version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest-browsers
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: .
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "61:52:fb:6d:6c:9c:fc:31:10:d3:be:54:4b:12:4a:cb"
      - run:
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  lint:
    executor: default
    steps:
      - attach
      - run:
          name: Lint
          command: |
            yarn lint --format junit --output-file reports/eslint/results.xml
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: dist
      - persist
  lhci:
    executor: default
    steps:
      - attach
      - run:
          name: Lighthouse
          command: |
            yarn lhci
      - store_artifacts:
          path: .lighthouseci
  deploy:
    executor: default
    parameters:
      stage:
        type: enum
        enum: [ "none", "dev" ]
    steps:
      - attach
      - ssh_keys
      - deploy:
          command: |
            yarn deploy -u "`git --no-pager show -s --format='%cn <%ce>' HEAD`" `[ "<< parameters.stage >>" = "none" ] && echo " -n"`


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - lhci:
          requires:
            - build
      - deploy:
          stage: none
          requires:
            - lint
            - build
          filters:
            branches:
              ignore: source
      - deploy:
          stage: dev
          requires:
            - lint
            - build
          filters:
            branches:
              only: source
